version: '0.1.2.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build ./src/Nancy.Metadata.Swagger.csproj -v quiet
  - cmd: dotnet publish ./src/Nancy.Metadata.Swagger.csproj -v quiet -f=netstandard1.6
artifacts:
  - path: '**\*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/nancy-metadata-swagger/api/v2/package
  on:
    branch: master  
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: true
