version: '0.1.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet publish ./src/Nancy.Metadata.Swagger.csproj -v quiet
artifacts:
  - path: '**\*.nupkg'
skip_commits:
  files:
    - '**/*.md'

