version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Nancy.Metadata.Swagger.csproj
build_script:
  - cmd: dotnet publish ./src/Nancy.Metadata.Swagger.csproj
artifacts:
  - path: '**\*.nupkg'
skip_commits:
  files:
    - '**/*.md'

