version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Nancy.Metadata.Swagger/Nancy.Metadata.Swagger.csproj
build_script:
  - cmd: dotnet publish ./Nancy.Metadata.Swagger/Nancy.Metadata.Swagger.csproj
